/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: cassiasilveira2004 (https://sketchfab.com/cassiasilveira2004)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/simple-road-texture1-41b5e535a9f7494a88f0e48819e3b744
title: Simple Road Texture1
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

import { GroupProps } from "@react-three/fiber";

const Model: React.FC<GroupProps> = (props) => {
  const { nodes, materials } = useGLTF("/road_straight.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane01_1.geometry}
        material={materials.Jezdnia_Kraweznik_MAT}
        position={[0.299, -1, -0.074]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
    </group>
  );
};

export default React.memo(Model);

useGLTF.preload("/road_straight.glb");
