/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 health/healthcare_model.glb 
Author: AlessioPassera (https://sketchfab.com/AlessioPassera)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-hospital-738972de7752491382457c068ab0a6ac
Title: Low Poly Hospital
*/

import { FC, memo } from "react";
import { useGLTF } from "@react-three/drei";

import { GroupProps } from "@react-three/fiber";

const Model: FC<GroupProps> = (props) => {
  const { nodes, materials } = useGLTF("/health/healthcare_model.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[-1225.551, 1212.31, 789.348]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Cube037_Colore_0.geometry}
            material={materials.Colore}
          />
          <mesh
            geometry={nodes.Cube037_Names_and_details_0.geometry}
            material={materials.Names_and_details}
          />
        </group>
        <group
          position={[0, 20, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.vetri_Vetro_0.geometry}
            material={materials.Vetro}
          />
          <mesh
            geometry={nodes.vetri_Vetro_alternate_0.geometry}
            material={materials.Vetro_alternate}
          />
        </group>
        <mesh
          geometry={nodes["(base)_hospital_Colore_0"].geometry}
          material={materials.Colore}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube025_Colore_0.geometry}
          material={materials.Colore}
          position={[0, 212.31, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube035_Colore_0.geometry}
          material={materials.Colore}
          position={[0, 20, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube036_Colore_0.geometry}
          material={materials.Colore}
          position={[0, 1788.238, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Plane014_Colore_0.geometry}
          material={materials.Colore}
          position={[-13.787, 740, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Plane015_Colore_0.geometry}
          material={materials.Colore}
          position={[400, 369.648, 500]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Plane016_Colore_0.geometry}
          material={materials.Colore}
          position={[400, 369.648, 500]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder009_Colore_0.geometry}
          material={materials.Colore}
          position={[1157.649, 437.612, 500]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Plane020_Colore_0.geometry}
          material={materials.Colore}
          position={[-1070.957, 1467.693, -532.923]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube056_Colore_0.geometry}
          material={materials.Colore}
          position={[-1004.915, 1467.693, -323.105]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube057_Colore_0.geometry}
          material={materials.Colore}
          position={[-1004.915, 1467.693, -323.105]}
          rotation={[-Math.PI / 2, 0, 1.257]}
          scale={100}
        />
        <mesh
          geometry={nodes.Text_Colore_0.geometry}
          material={materials.Colore}
          position={[400, 761.97, 483.583]}
          rotation={[0, Math.PI / 2, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Plane023_Colore_0.geometry}
          material={materials.Colore}
          position={[-13.787, 1147.589, -1438.999]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube060_Colore_0.geometry}
          material={materials.Colore}
          position={[444.812, 20, 808.245]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube061_Colore_0.geometry}
          material={materials.Colore}
          position={[-592.082, 166.198, 1411.648]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Text001_Colore_0.geometry}
          material={materials.Colore}
          position={[-592.082, 202.084, 1423.937]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube062_Colore_0.geometry}
          material={materials.Colore}
          position={[-592.082, 166.198, 1411.648]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube055_Colore_0.geometry}
          material={materials.Colore}
          position={[0, 20, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.frames_Colore_0.geometry}
          material={materials.Colore}
          position={[0, 20, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube058_Colore_0.geometry}
          material={materials.Colore}
          position={[0, 20, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube059_Colore_0.geometry}
          material={materials.Colore}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder019_Colore_0.geometry}
          material={materials.Colore}
          position={[761.804, 1112.31, -500]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
};

export default memo(Model);

useGLTF.preload("/health/healthcare_model.glb");
