/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 city/skyscraperC.glb 
*/

import { FC, memo } from "react";
import { useGLTF } from "@react-three/drei";

import { GroupProps } from "@react-three/fiber";

const Model: FC<GroupProps> = (props) => {
  const { nodes, materials } = useGLTF("/city/skyscraperC.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_skyscraperC.geometry}
        material={materials.window}
      />
      <mesh
        geometry={nodes.Mesh_skyscraperC_1.geometry}
        material={materials.trim}
      />
      <mesh
        geometry={nodes.Mesh_skyscraperC_2.geometry}
        material={materials.door}
      />
      <mesh
        geometry={nodes.Mesh_skyscraperC_3.geometry}
        material={materials.border}
      />
      <mesh
        geometry={nodes.Mesh_skyscraperC_4.geometry}
        material={materials._defaultMat}
      />
      <mesh
        geometry={nodes.Mesh_skyscraperC_5.geometry}
        material={materials.roof}
      />
    </group>
  );
};

export default memo(Model);

useGLTF.preload("/city/skyscraperC.glb");
