/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 city/small_buildingD.glb 
*/

import { FC, memo } from "react";
import { useGLTF } from "@react-three/drei";

import { GroupProps } from "@react-three/fiber";

const Model: FC<GroupProps> = (props) => {
  const { nodes, materials } = useGLTF("/city/small_buildingD.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_small_buildingD.geometry}
        material={materials.border}
      />
      <mesh
        geometry={nodes.Mesh_small_buildingD_1.geometry}
        material={materials._defaultMat}
      />
      <mesh
        geometry={nodes.Mesh_small_buildingD_2.geometry}
        material={materials.door}
      />
      <mesh
        geometry={nodes.Mesh_small_buildingD_3.geometry}
        material={materials.window}
      />
      <mesh
        geometry={nodes.Mesh_small_buildingD_4.geometry}
        material={materials.roof}
      />
    </group>
  );
};

export default memo(Model);

useGLTF.preload("/city/small_buildingD.glb");
