/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 low_poly_trees.glb 
Author: Aditya Graphical (https://sketchfab.com/Adityakm)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-trees-51cae4a194344e8bbfbd0a4cff205f76
Title: Low poly trees
*/

import { FC, memo } from "react";
import { useGLTF } from "@react-three/drei";

import { GroupProps } from "@react-three/fiber";

interface TreesProps extends GroupProps {
  selectedMeshName: string;
}

const Model: FC<TreesProps> = ({ selectedMeshName, ...props }) => {
  const { nodes, materials } = useGLTF("/low_poly_trees.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        {selectedMeshName === "_1_tree__1_tree_0" && (
          <mesh
            geometry={nodes._1_tree__1_tree_0.geometry}
            material={materials["1_tree"]}
            position={[-358.535, -1.165, 2.407]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[38.657, 38.657, 29.012]}
          />
        )}
        {selectedMeshName === "_2_tree__2_tree_0" && (
          <mesh
            geometry={nodes._2_tree__2_tree_0.geometry}
            material={materials["2_tree"]}
            position={[-252.286, -1.165, 2.407]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={22.623}
          />
        )}
        {selectedMeshName === "_3_tree__3_tree_0" && (
          <mesh
            geometry={nodes._3_tree__3_tree_0.geometry}
            material={materials["3_tree"]}
            position={[-133.947, -1.165, 2.407]}
            rotation={[-0.359, -0.228, -0.067]}
            scale={[20.443, 25.444, 20.443]}
          />
        )}
        {selectedMeshName === "_4_tree__4_tree_0" && (
          <mesh
            geometry={nodes._4_tree__4_tree_0.geometry}
            material={materials["4_tree"]}
            position={[-18.233, -1.165, 2.407]}
            rotation={[2.586, -1.382, -2.872]}
            scale={[7.688, 14.399, 4.733]}
          />
        )}
        {selectedMeshName === "_5_tree__5_tree_0" && (
          <mesh
            geometry={nodes._5_tree__5_tree_0.geometry}
            material={materials["5_tree"]}
            position={[91.732, -2.326, 3.375]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[18.411, 18.411, 31.888]}
          />
        )}
        {selectedMeshName === "_6_tree__6_tree_0" && (
          <mesh
            geometry={nodes._6_tree__6_tree_0.geometry}
            material={materials["6_tree"]}
            position={[256.661, -2.326, 3.375]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={13.486}
          />
        )}
        {selectedMeshName === "_7_tree__7_tree_0" && (
          <mesh
            geometry={nodes._7_tree__7_tree_0.geometry}
            material={materials["7_tree"]}
            position={[403.828, -1.165, 2.407]}
            rotation={[-1.22, 0.041, -2.69]}
            scale={[29.383, 29.383, 40.782]}
          />
        )}
        {selectedMeshName === "_10_tree__10_tree_0" && (
          <mesh
            geometry={nodes._10_tree__10_tree_0.geometry}
            material={materials["10_tree"]}
            position={[806.036, -2.465, 9.754]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={4.84}
          />
        )}
        {selectedMeshName === "_11_tree__11_tree_0" && (
          <mesh
            geometry={nodes._11_tree__11_tree_0.geometry}
            material={materials["11_tree"]}
            position={[946.038, -2.465, 9.754]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={8.862}
          />
        )}
        {selectedMeshName === "_12_tree__12_tree_0" && (
          <mesh
            geometry={nodes._12_tree__12_tree_0.geometry}
            material={materials["12_tree"]}
            position={[1048.779, -2.465, 9.754]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={12.614}
          />
        )}
        {selectedMeshName === "_8_tree__8_tree_0" && (
          <mesh
            geometry={nodes._8_tree__8_tree_0.geometry}
            material={materials["8_tree"]}
            position={[540.596, -2.465, 9.754]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={6.046}
          />
        )}
        {selectedMeshName === "_9_tree__9_tree_0" && (
          <mesh
            geometry={nodes._9_tree__9_tree_0.geometry}
            material={materials["9_tree"]}
            position={[657.947, -2.28, 9.754]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={3.32}
          />
        )}
        {selectedMeshName === "Rock_1__Rock_1__0" && (
          <mesh
            geometry={nodes.Rock_1__Rock_1__0.geometry}
            material={materials.Rock_1}
            position={[1263.794, -5.474, 48.395]}
            rotation={[-Math.PI / 2, 0, -1.854]}
            scale={[28.408, 28.408, 43.808]}
          />
        )}
      </group>
    </group>
  );
};

export default memo(Model);

useGLTF.preload("/low_poly_trees.glb");
